### ISSUE TITLE
xBArticleMan -New version - new error

### ISSUE THREAD

**Issue by BernSgo** [rogercreagh/joomla-xbArticleMan#3]
**Describe the bug**
After yesterday update the old error message disappears, but a new one is there

**To Reproduce**

**Expected behavior**

**Screenshots**
![xbArticleMan_Dienstag, 11  Juni 2024_08h16m11s_001_](https://github.com/rogercreagh/joomla-xbArticleMan/assets/165266578/4371434c-4d92-4bb2-8939-8a2be5801dbf)

**Server (please provide details from Joomla system info page)**
the same as yesterday

**Desktop Client (please complete the following information):**
 same as yesterday

**Smartphone**

**Additional context**
It is a great tool, thanks for this - Bernhard

**Comment by BernSgo** [comment]
Hi Roger,

it's me again. I attach an error log for you

Bernhard
[xbArticleMan - Error Log.txt](https://github.com/user-attachments/files/15783749/xbArticleMan.-.Error.Log.txt)

**Comment by rogercreagh** [comment]
Hmm, that's odd as it appears to be an error in a regular expression used to find shortcodes in the database - but the existing code works fine on J5.1 and hasn't changed since the original J3 release. I suspect it might be either a language difference of a particular version of MySQL on your install - it is very difficult to test all possible variations.

If this is the case I might expect the ArtShortcodes view also to generate an error

I have made a (informed!) guess at a possible cause and posted a new version in the `releases` folder on here. Could you try downloading and installing v5.0.0.3-beta1 and let me know if it has fixed the problem. Could you also post a screenshot of the Joomla System information page from the admin menu - I'm particularly looking for the Database type and version and the PHP and Joomla versions

**Comment by rogercreagh** [comment]
Just to clarify @BernSgo you are using the Joomla 5 version aren't you? This issue is in the J3 version which I didn't notice. The new beta version is in the other repo here https://github.com/rogercreagh/j5-xbArticleMan/releases/download/v5.0.0.3-beta-1/com_xbarticleman-j5_v5.0.0.3-beta1.zip 

I'll close this issue and open a fresh one in the correct repository

**Comment by rogercreagh** [comment]
See new issue here https://github.com/rogercreagh/j5-xbArticleMan/issues/4
